// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

// eslint-disable-next-line import/prefer-default-export
export const components = {
  blog_content: dynamic(() => import("./BlogContent")),
  blog_quote: dynamic(() => import("./BlogQuote")),
};
